# Generated by Django 4.2.7 on 2026-03-18 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Black', 'Black'), ('White', 'White'), ('Silver', 'Silver'), ('Space Gray', 'Space Gray'), ('Gold', 'Gold'), ('Rose Gold', 'Rose Gold'), ('Red', 'Red (Product RED)'), ('Blue', 'Blue'), ('Purple', 'Purple'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Pacific Blue', 'Pacific Blue'), ('Graphite', 'Graphite'), ('Sierra Blue', 'Sierra Blue'), ('Alpine Green', 'Alpine Green'), ('Deep Purple', 'Deep Purple'), ('Starlight', 'Starlight'), ('Midnight', 'Midnight'), ('Pink', 'Pink'), ('Light Blue', 'Light Blue'), ('Dark Cherry', 'Dark Cherry'), ('Titanium', 'Titanium'), ('Natural Titanium', 'Natural Titanium'), ('Blue Titanium', 'Blue Titanium'), ('White Titanium', 'White Titanium'), ('Black Titanium', 'Black Titanium'), ('Desert Titanium', 'Desert Titanium')], max_length=50, unique=True)),
                ('hex_code', models.CharField(default='#000000', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='iPhoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('iPhone 6', 'iPhone 6'), ('iPhone 6 Plus', 'iPhone 6 Plus'), ('iPhone 6s', 'iPhone 6s'), ('iPhone 6s Plus', 'iPhone 6s Plus'), ('iPhone SE (1st gen)', 'iPhone SE (1st gen)'), ('iPhone 7', 'iPhone 7'), ('iPhone 7 Plus', 'iPhone 7 Plus'), ('iPhone 8', 'iPhone 8'), ('iPhone 8 Plus', 'iPhone 8 Plus'), ('iPhone X', 'iPhone X'), ('iPhone XR', 'iPhone XR'), ('iPhone XS', 'iPhone XS'), ('iPhone XS Max', 'iPhone XS Max'), ('iPhone 11', 'iPhone 11'), ('iPhone 11 Pro', 'iPhone 11 Pro'), ('iPhone 11 Pro Max', 'iPhone 11 Pro Max'), ('iPhone SE (2nd gen)', 'iPhone SE (2nd gen)'), ('iPhone 12 mini', 'iPhone 12 mini'), ('iPhone 12', 'iPhone 12'), ('iPhone 12 Pro', 'iPhone 12 Pro'), ('iPhone 12 Pro Max', 'iPhone 12 Pro Max'), ('iPhone 13 mini', 'iPhone 13 mini'), ('iPhone 13', 'iPhone 13'), ('iPhone 13 Pro', 'iPhone 13 Pro'), ('iPhone 13 Pro Max', 'iPhone 13 Pro Max'), ('iPhone SE (3rd gen)', 'iPhone SE (3rd gen)'), ('iPhone 14', 'iPhone 14'), ('iPhone 14 Plus', 'iPhone 14 Plus'), ('iPhone 14 Pro', 'iPhone 14 Pro'), ('iPhone 14 Pro Max', 'iPhone 14 Pro Max'), ('iPhone 15', 'iPhone 15'), ('iPhone 15 Plus', 'iPhone 15 Plus'), ('iPhone 15 Pro', 'iPhone 15 Pro'), ('iPhone 15 Pro Max', 'iPhone 15 Pro Max'), ('iPhone 16', 'iPhone 16'), ('iPhone 16 Plus', 'iPhone 16 Plus'), ('iPhone 16 Pro', 'iPhone 16 Pro'), ('iPhone 16 Pro Max', 'iPhone 16 Pro Max'), ('iPhone 17', 'iPhone 17'), ('iPhone 17 Plus', 'iPhone 17 Plus'), ('iPhone 17 Pro', 'iPhone 17 Pro'), ('iPhone 17 Pro Max', 'iPhone 17 Pro Max')], max_length=50, unique=True)),
                ('release_year', models.IntegerField()),
                ('display_size', models.CharField(max_length=20)),
                ('storage_options', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-release_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='iPhoneProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage', models.CharField(choices=[('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('512GB', '512GB'), ('1TB', '1TB'), ('2TB', '2TB')], max_length=10)),
                ('condition', models.CharField(choices=[('new', 'New'), ('refurbished', 'Refurbished'), ('used', 'Used')], default='new', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='iphone_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.color')),
                ('iphone_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.iphonemodel')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('iphone_model', 'color', 'storage', 'condition')},
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.iphoneproduct')),
            ],
            options={
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
