# Generated by Django 4.2.7 on 2026-03-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_shippingtracking_shippingupdate_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='iphoneproduct',
            name='cover_photo',
            field=models.ImageField(blank=True, help_text='Main cover photo for product listing', null=True, upload_to='iphone_covers/'),
        ),
    ]
