# Generated by Django 4.2.7 on 2026-03-18 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_iphoneproduct_cover_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingupdate',
            options={},
        ),
        migrations.CreateModel(
            name='iPhoneModelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='iphone_model_images/')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary image for this color variant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_images', to='store.color')),
                ('iphone_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_images', to='store.iphonemodel')),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
                'unique_together': {('iphone_model', 'color', 'is_primary')},
            },
        ),
    ]
