# Generated by Django 4.2.7 on 2026-03-19 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_shippingupdate_options_iphonemodelimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingupdate',
            options={'ordering': ['-timestamp']},
        ),
        migrations.DeleteModel(
            name='iPhoneModelImage',
        ),
    ]
