# Generated by Django 4.2.7 on 2026-03-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_shippingupdate_options_delete_iphonemodelimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='iphoneproduct',
            name='grade',
            field=models.CharField(choices=[('A', 'Grade A - Excellent'), ('B', 'Grade B - Good'), ('C', 'Grade C - Fair'), ('D', 'Grade D - Poor')], default='A', max_length=20),
        ),
    ]
