# Generated by Django 4.2.7 on 2026-03-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_iphoneproduct_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iphoneproduct',
            name='grade',
            field=models.CharField(choices=[('A', 'Grade A - Best'), ('B', 'Grade B - Good'), ('C', 'Grade C - Better')], default='A', max_length=20),
        ),
    ]
