# Generated by Django 4.2.7 on 2026-04-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_iphoneproduct_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='pf_amount_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pf_amount_gross',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pf_amount_net',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pf_m_payment_id',
            field=models.CharField(blank=True, help_text='PayFast Merchant Payment ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pf_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pf_payment_id',
            field=models.CharField(blank=True, help_text='PayFast Payment ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pf_payment_status',
            field=models.CharField(blank=True, help_text='PayFast Payment Status', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pf_transaction_id',
            field=models.CharField(blank=True, help_text='PayFast Transaction ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20),
        ),
    ]
